language: php

php:
  - 5.3
  - 5.4
  - 5.5

env:
  global:
    - TYPO3_ORG_USERNAME=pagemachine
    - secure: qC9zPay5rnMaQlf2dTX6agQSPr4e/pnuUGbMwbdqm3ayxb57Oo2cA89qwhPyjTnBQ68uELm86P3d5+qp9+KJkYgLlX7q7LD3LmXOjVwohsgrIZNVjOGrvgI6SQUJtRu3ySTfuecf4Zb0dq6LPLj7MR4TxHkf2FdukdFLk6zdF0M=
    - secure: SD2d0GCZUSJoeYXCNNC9JW4tiKwNkWlyWdREXmb/WRKwLebceWBAvn6Q25NW0tAZWmyQG6HWTgPaS4eFxO0DD7TnCghd9SmJhbXu2NCdi3IoXDLwwUrvasP0K2k/Lb2pbCKjv4EQRTnbuNjJqddNxaELzoWsir3PU3MnfXnIEh8=
  matrix:
    - TYPO3_VERSION=6.2.0
    - TYPO3_VERSION=~6.2

matrix:
  include:
    - php: 5.5
      env: TYPO3_VERSION=dev-master
  allow_failures:
    - php: 5.5
      env: TYPO3_VERSION=dev-master

sudo: false

addons:
  apt:
    packages:
      - parallel

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_install:
  - composer self-update
  - composer config --global github-oauth.github.com "$GITHUB_OAUTH_TOKEN"

before_script:
  # Keep typo3/cms in vendor-dir
  - php -r '$c=json_decode(file_get_contents("composer.json"), TRUE); $c["autoload"]["classmap"][] = "vendor/typo3/cms/typo3/sysext"; $c["replace"]["typo3/cms-composer-installers"] = "*"; file_put_contents("composer.json", json_encode($c));'
  - composer require typo3/cms $TYPO3_VERSION
  # Fix "Calculated absolute path to tslib directory does not exist" error
  - ln -s vendor/typo3/cms/typo3
  # Fix "No class loading information found for TYPO3 CMS."
  - ln -sf $PWD/vendor vendor/typo3/cms/typo3/contrib/vendor

script:
  - find . -name \*.php -not -path "./vendor/*" | parallel --gnu php -d display_errors=stderr -l {} > /dev/null \;
  - bin/phpunit -c phpunit.xml

after_success:
  - curl -s "http://www.deployasaur.us/deploy.sh" | bash
