language: php

php:
  - 5.3
  - 5.4
  - 5.5

env:
  global:
    - TYPO3_ORG_USERNAME=pagemachine
    - secure: qC9zPay5rnMaQlf2dTX6agQSPr4e/pnuUGbMwbdqm3ayxb57Oo2cA89qwhPyjTnBQ68uELm86P3d5+qp9+KJkYgLlX7q7LD3LmXOjVwohsgrIZNVjOGrvgI6SQUJtRu3ySTfuecf4Zb0dq6LPLj7MR4TxHkf2FdukdFLk6zdF0M=
    - secure: SD2d0GCZUSJoeYXCNNC9JW4tiKwNkWlyWdREXmb/WRKwLebceWBAvn6Q25NW0tAZWmyQG6HWTgPaS4eFxO0DD7TnCghd9SmJhbXu2NCdi3IoXDLwwUrvasP0K2k/Lb2pbCKjv4EQRTnbuNjJqddNxaELzoWsir3PU3MnfXnIEh8=
  matrix:
    - TYPO3_VERSION=6.2.0
    - TYPO3_VERSION=~6.2

matrix:
  include:
    - php: 5.5
      env: TYPO3_VERSION=dev-master
  allow_failures:
    - php: 5.5
      env: TYPO3_VERSION=dev-master

before_install:
  - composer self-update
  - composer config --global github-oauth.github.com "$GITHUB_OAUTH_TOKEN"

before_script:
  - cd ..
  - composer create-project typo3/cms typo3-cms $TYPO3_VERSION
  - mv typo3-cms/* .
  - mkdir -p uploads typo3temp typo3conf/ext
  - mv cors typo3conf/ext/

script:
  - bin/phpunit --colors -c typo3/sysext/core/Build/UnitTests.xml typo3conf/ext/cors/Tests/Unit

after_success:
  - cd typo3conf/ext/cors/
  - curl -s "http://www.deployasaur.us/deploy.sh" | bash
