language: php

php:
  - 5.3
  - 5.4
  - 5.5

env:
  global:
    - TYPO3_ORG_USERNAME=pagemachine
    - secure: qC9zPay5rnMaQlf2dTX6agQSPr4e/pnuUGbMwbdqm3ayxb57Oo2cA89qwhPyjTnBQ68uELm86P3d5+qp9+KJkYgLlX7q7LD3LmXOjVwohsgrIZNVjOGrvgI6SQUJtRu3ySTfuecf4Zb0dq6LPLj7MR4TxHkf2FdukdFLk6zdF0M=
    - secure: SD2d0GCZUSJoeYXCNNC9JW4tiKwNkWlyWdREXmb/WRKwLebceWBAvn6Q25NW0tAZWmyQG6HWTgPaS4eFxO0DD7TnCghd9SmJhbXu2NCdi3IoXDLwwUrvasP0K2k/Lb2pbCKjv4EQRTnbuNjJqddNxaELzoWsir3PU3MnfXnIEh8=
  matrix:
    - TYPO3_BRANCH=TYPO3_6-2

matrix:
  include:
    - php: 5.5
      env: TYPO3_BRANCH=master

before_script:
  - cd ..
  - git clone --single-branch --branch $TYPO3_BRANCH --depth 1 https://github.com/TYPO3/TYPO3.CMS.git typo3_core
  - mv typo3_core/* .
  - sudo apt-get install parallel
  - composer self-update
  - composer config github-oauth.github.com "$GITHUB_OAUTH_TOKEN"
  - composer install
  - mkdir -p uploads typo3temp typo3conf/ext
  - mv cors typo3conf/ext/

script:
  - ./bin/phpunit --colors -c typo3/sysext/core/Build/UnitTests.xml typo3conf/ext/cors/Tests/Unit

after_success:
  - curl -s "http://www.deployasaur.us/deploy.sh" | bash
