language: php

php:
  - 5.3
  - 5.5

env:
  global:
    - TYPO3_ORG_USERNAME=pagemachine
    - secure: qC9zPay5rnMaQlf2dTX6agQSPr4e/pnuUGbMwbdqm3ayxb57Oo2cA89qwhPyjTnBQ68uELm86P3d5+qp9+KJkYgLlX7q7LD3LmXOjVwohsgrIZNVjOGrvgI6SQUJtRu3ySTfuecf4Zb0dq6LPLj7MR4TxHkf2FdukdFLk6zdF0M=
    - secure: SD2d0GCZUSJoeYXCNNC9JW4tiKwNkWlyWdREXmb/WRKwLebceWBAvn6Q25NW0tAZWmyQG6HWTgPaS4eFxO0DD7TnCghd9SmJhbXu2NCdi3IoXDLwwUrvasP0K2k/Lb2pbCKjv4EQRTnbuNjJqddNxaELzoWsir3PU3MnfXnIEh8=
  matrix:
    - TYPO3_VERSION=6.2.0 TYPO3_SIX=1
    - TYPO3_VERSION=~6.2 TYPO3_SIX=1

matrix:
  include:
    - php: 5.5
      env: TYPO3_VERSION=dev-master
  allow_failures:
    - php: 5.5
      env: TYPO3_VERSION=dev-master

sudo: false

addons:
  apt:
    packages:
      - parallel

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer self-update
  - composer config --global github-oauth.github.com "$GITHUB_OAUTH_TOKEN"

before_script:
  # Make sure TYPO3 6.2 uses the latest installers package
  - >
    if [[ -n "$TYPO3_SIX" ]]; then
      composer require typo3/cms-composer-installers "1.2.2 as 1.1.4"
    fi;
  - composer require typo3/cms $TYPO3_VERSION
  - npm install
  - export PATH="$(npm bin):$PATH"

script:
  - find . -name \*.php ! -path "./.vendor/*" | parallel --gnu php -d display_errors=stderr -l {} > /dev/null \;
  - .vendor/bin/phpunit

after_script:
  - >
    if [ -n "$TRAVIS_TAG" ]; then
      echo -e "Preparing upload of release ${TRAVIS_TAG} to TER\n"
      travis-after-all;
      if [ $? -eq 0 ]; then
        TAG_ANNOTATION="$(git tag -n -l $TRAVIS_TAG)"
        TAG_MESSAGE="${TAG_ANNOTATION#* }"
        echo "Uploading release ${TRAVIS_TAG} to TER"
        rm -rf node_modules
        .vendor/bin/upload . $TYPO3_ORG_USERNAME $TYPO3_ORG_PASSWORD "$TAG_MESSAGE"
      fi;
    fi;
  - >
