language: php

php:
  - 5.3
  - 5.5
  - 5.6

env:
  global:
    - TYPO3_ORG_USERNAME=pagemachine
    - secure: qC9zPay5rnMaQlf2dTX6agQSPr4e/pnuUGbMwbdqm3ayxb57Oo2cA89qwhPyjTnBQ68uELm86P3d5+qp9+KJkYgLlX7q7LD3LmXOjVwohsgrIZNVjOGrvgI6SQUJtRu3ySTfuecf4Zb0dq6LPLj7MR4TxHkf2FdukdFLk6zdF0M=
    - secure: SD2d0GCZUSJoeYXCNNC9JW4tiKwNkWlyWdREXmb/WRKwLebceWBAvn6Q25NW0tAZWmyQG6HWTgPaS4eFxO0DD7TnCghd9SmJhbXu2NCdi3IoXDLwwUrvasP0K2k/Lb2pbCKjv4EQRTnbuNjJqddNxaELzoWsir3PU3MnfXnIEh8=
  matrix:
    - TYPO3_VERSION=^6.2.20

matrix:
  include:
    - php: 5.5
      env: TYPO3_VERSION=^7.6
    - php: 5.6
      env: TYPO3_VERSION=^7.6
    - php: 7.0
      env: TYPO3_VERSION=^7.6

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer self-update
  - composer config --global github-oauth.github.com "$GITHUB_OAUTH_TOKEN"

before_script:
  - composer require typo3/cms $TYPO3_VERSION

script:
  - bin/parallel-lint --exclude bin --exclude vendor --exclude web .
  - bin/phpunit

after_script:
  - >
    if [ -n "$TRAVIS_TAG" ]; then
      echo -e "Preparing upload of release ${TRAVIS_TAG} to TER\n"

      export PATH=$HOME/.composer/vendor/bin:$(npm bin):$PATH
      npm install
      travis-after-all;

      if [ $? -eq 0 ]; then
        TAG_ANNOTATION="$(git tag -n -l $TRAVIS_TAG)"
        TAG_MESSAGE="${TAG_ANNOTATION#* }"

        git reset --hard
        git clean -xfd

        composer global require namelesscoder/typo3-repository-client:^1.1.1

        echo "Uploading release ${TRAVIS_TAG} to TER"
        upload . $TYPO3_ORG_USERNAME $TYPO3_ORG_PASSWORD "$TAG_MESSAGE"
      fi;
    fi;

notifications:
  slack:
    secure: FHPbVXHOrXsk80e0+WLID8v5m9S59/qoQyM5XK2hytFUaT+oSh0iY+Ajdnajpl+6qd6iQNbREfd04A2TTBxh7+LzHgOqxhHoZSYTgTHgsOPQPgUCxPJpWInwQGxgp+23pE0l+oX8u0lWkYk9NIf+WtrF6niLvT0KLOJiuB8ojms=
